#version 430 core

layout(local_size_x = 256) in;

struct Edge {
    uvec4 topology;
    ivec4 levels;
};

layout(std430, binding = 0) readonly buffer Edges {
    Edge edges[];
};

layout(std430, binding = 1) writeonly buffer VisibleEdges {
    uint visibleEdgeIds[];
};

layout(std430, binding = 2) buffer DrawCommand {
    uint count;
    uint instanceCount;
    uint first;
    uint baseInstance;
} command;

uniform uint uEdgeCount;
uniform int uLevel;

void main() {
    uint edgeId = gl_GlobalInvocationID.x;
    if (edgeId >= uEdgeCount) {
        return;
    }

    int birthLevel = edges[edgeId].levels.x;
    int deathLevel = edges[edgeId].levels.y;
    if (birthLevel < 0 || deathLevel < 0 || uLevel > birthLevel || uLevel < deathLevel) {
        return;
    }

    uint vertexOffset = atomicAdd(command.count, 2u);
    visibleEdgeIds[vertexOffset >> 1u] = edgeId;
}
