#version 450 core
layout(local_size_x = 1) in;

layout(std430, binding = 0) readonly buffer DrawCounter { uint drawCount; };
layout(std430, binding = 1) writeonly buffer DrawCommand {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint baseInstance;
};

uniform uint uDrawCapacity;

void main() {
    uint count = min(drawCount, uDrawCapacity);
    vertexCount = count * 2u;
    instanceCount = 1u;
    firstVertex = 0u;
    baseInstance = 0u;
}
