#version 450 core
layout(local_size_x = 1) in;

layout(std430, binding = 0) readonly buffer Counter { uint itemCount; };
layout(std430, binding = 1) writeonly buffer DispatchCommand {
    uint groupsX;
    uint groupsY;
    uint groupsZ;
};

uniform uint uLocalSize;

void main() {
    uint size = max(uLocalSize, 1u);
    groupsX = (itemCount + size - 1u) / size;
    groupsY = 1u;
    groupsZ = 1u;
}
