#version 430 core

layout(local_size_x = 1) in;

layout(std430, binding = 0) readonly buffer InputDrawCommand {
    uint inputVertexCount;
    uint inputInstanceCount;
    uint inputFirst;
    uint inputBaseInstance;
};

layout(std430, binding = 1) buffer DispatchCommand {
    uint groupsX;
    uint groupsY;
    uint groupsZ;
} dispatchCommand;

const uint WorkGroupSize = 256u;

void main() {
    uint edgeCount = inputVertexCount >> 1u;
    dispatchCommand.groupsX = (edgeCount + WorkGroupSize - 1u) / WorkGroupSize;
    dispatchCommand.groupsY = 1u;
    dispatchCommand.groupsZ = 1u;
}
