#version 430 core

layout(local_size_x = 1) in;

layout(std430, binding = 0) readonly buffer OutputCounter {
    uint outputEdgeCount;
};

layout(std430, binding = 1) buffer DrawCommand {
    uint count;
    uint instanceCount;
    uint first;
    uint baseInstance;
} command;

uniform uint uOutputCapacity;

void main() {
    command.count = min(outputEdgeCount, uOutputCapacity) * 2u;
    command.instanceCount = 1u;
    command.first = 0u;
    command.baseInstance = 0u;
}
